### ISSUE TITLE
API for retrieving list of items in a page

### ISSUE THREAD

**Issue by chinathaip** [stamford-syntax-club/stamfordcenter-backend#15]
## Story
The content inside Stamford Center changes regularly. This means that the content displayed on the frontend should not be static, rather should be retrieved from the backend. This task creates a RESTful API endpoint to allow such functionality

The contents to display are managed by the Admin Panel, we simply provide a way to access such contents
### Spec
```
/api/resources/<page_name>
```

Example: 
```
/api/resources/studyplans = retrieve list of items inside the study_plans
/api/resources/resources = retrieve list of items inside the resources
```

## Todo
- [X] MongoDB Instance: (TBD)
  - each page has its own collection
  - i.e. study plans, announcement, resourcesetc.

- [X] `/api/resources/<....>` to retrieve list of items

    **Example**: `GET /api/resources/resources` (retrieve list of items in academic resources page)
   - Response (Note: response for each page will differ)
```json
[
  {
    "name": "Class Schedules & Full Name Lists",
    "iconURL": "<DYNAMIC_HOST>/api/files/resources/class_schedules_icon.png",
    "files": [
      {
        "name": "UG Class Schedule Term 1-2023",
        "url": "<DYNAMIC_HOST>/api/files/resources/1_2023_class_schedule.pdf"
      }
    ]
  },
  {
    "name": "Academic Calendars",
    "iconURL": "<DYNAMIC_HOST>/api/files/resources/academic_calendars_icon.png",
    "files": [
      {
        "name": "Academic Calendar Term 1-2023",
        "url": "<DYNAMIC_HOST>/api/files/resources/1_2023_academic_calendar.pdf"
      },
      {
        "name": "Academic Calendar Term 2-2023",
        "url": "<DYNAMIC_HOST>/api/files/2_2023_academic_calendar.pdf"
      }
    ]
  },
.... more
```
     Value of DYNAMIC HOST will be:
        - https://center-be.stamford.dev if NODE_ENV is production
               - this is set as default after the image is built
       - https://center-be-beta.stamford.dev if NODE_ENV is beta
               - we can set this in docker-compose.dev.yaml (https://github.com/orgs/stamford-syntax-club/teams/ssc-platform will handle this)
       - http://localhost:<PORT> if nothing matches (run locally)
- [ ] migrate `/api/study_plans` to `/api/resources/studyplans`
  - inform frontend about this change, don't remove the old endpoint until frontend finally migrates
  - remove the files in root dir in s3 bucket after this (`s3://stamford-center/<file-name>`)

**Comment by chinathaip** [comment]
Separated pages into collections

![Image](https://github.com/stamford-syntax-club/stamfordcenter-backend/assets/92321280/42234d0f-36f1-480b-801f-5e0166897316)
